### ISSUE TITLE
When changing the username format order, the default order is always being used

### ISSUE THREAD

**Issue by emyb** [troywilliams/moodle-enrol_arlo#3]
It appears that changing the username format order will always apply the default order. I have checked the settings, the plugin config table, and synchronised new contacts (users) into courses and have observed the firstname lastname random number format is always used.

I have some screenshots.

**The screenshot below is a shot of the settings that I have changed.**
<img width="1257" alt="Screen Shot 2019-05-17 at 9 11 26 AM" src="https://user-images.githubusercontent.com/28742087/57887696-44fda300-7884-11e9-8c12-f9dfb51fa843.png">

**The screenshot below is of a print_object() function call showing what order has been used. It should be the order in the screenshot following this screenshot.**
<img width="763" alt="Screen Shot 2019-05-17 at 9 10 10 AM" src="https://user-images.githubusercontent.com/28742087/57887868-b8071980-7884-11e9-9e77-30389a8997ed.png">

**The screenshot below is the one mentioned in the screenshot above. This shows what the config_plugins table is returning for the enrol_arlo plugin**
<img width="812" alt="Screen Shot 2019-05-17 at 9 11 17 AM" src="https://user-images.githubusercontent.com/28742087/57887891-c48b7200-7884-11e9-9ffc-3a67a0261f18.png">

Please please, get in touch if you require any further details.

**Comment by troywilliams** [comment]
@emyb Fixed at https://github.com/troywilliams/moodle-enrol_arlo/commit/864e8d5a152a0cd50ce0e07932dca9f3b11a7196

Thanks for your help 🥇
